### ISSUE TITLE
Remove the force-uninstall `/sw.js` 

### ISSUE THREAD

**Issue by giac-mysten** [MystenLabs/walrus-sites#101]

**Comment by Tzal3x** [comment]
Hey @giac-mysten! From what I understand this issue indicates that the `sw.js` should be removed. 

But the `sw.js` should -quoting- [_"be removed after sufficient time has passed"_](https://github.com/MystenLabs/walrus-sites/pull/100). 
Can you elaborate on that? 
Should I implement this or wait for the aforementioned condition?
Cheers!

**Comment by giac-mysten** [comment]
> Can you elaborate on that?

the problem is the following: if anyone had loaded a walrus site at the very launch of walrus, they may still have `sw.js` installed in their browser. The new `sw.js` uninstalls the old one and forces a reload, fixing the problem. Essentially, we need to wait long enough that anyone that may have used the old `sw.js` has reloaded and installed the new one.

> Should I implement this or wait for the aforementioned condition?

I think we can wait a bit longer, there is no rush
