### ISSUE TITLE
[Major Feature]: add wildcard paths to allow HTML5-based routing.

### ISSUE THREAD

**Issue by giac-mysten** [MystenLabs/walrus-sites#116]
At the moment, [HTML5-based routing](https://medium.com/byteagenten/integrating-html5-routing-in-a-java-web-application-e55adeee77d) probably does not work, because the routing of Walrus Sites requires an exact match of the URL path on the list of paths that are in the Sui object for the site.

A bit of design may be needed, but this would be great to enable existing JS tooling to be used with walrus sites.

#### Another default `404.html`

Currently, if the portal/SW do not find a path, they revert to `/404.html` if it exists. 

https://github.com/MystenLabs/walrus-sites/blob/9aad845f30a1e33f0aa4998c6b8a54b84f63b232/portal/src/walrus-sites-sw.ts#L287-L293

As a first step, we may want to allow setting a `/walrus-sites-default.html`, which, if it exists, gets loaded when no other path is found.

Pros:
- Very simple
- Allows for simple one page apps
- Only requires modifying the SW/portal logic

Cons:
- Does not fully capture the full potential of HTML5-based routing
- Introduces more "special files" (the default) that are Walrus sites specific

#### Contract-side defaults

We could achieve something similar to the above, but without special files, by adding a field in the `Site` object on chain that specifies the default Resource for the site

Pros / cons :
- Same as above, except it requires modifying both SW/portal and contracts
- Does not require special files

#### Wildcard paths

One possible solution would be to allow "wildcard" paths for resources. I.e., `/view/*`  points to blob id `asdf...`, so that the root of the path determines what resources are loaded, and within those resources there is the  code to interpret the rest of the url.

Pros:
- Does not require contract changes (except see cons below)
- Flexible: we can specify many different default resources

Cons:
- it requires checking that any prefix of the path exists as a wildcalrd path in the service workers
- we may need to enforce that there are no conflicting wildcard paths (in Move?)

**Comment by rjs-mysten** [comment]
If we go with wildcard paths, we should probably use a syntax similar to nginx rewrite rules ( https://www.digitalocean.com/community/tutorials/nginx-rewrite-url-rules )

**Comment by Tzal3x** [comment]
Closing the issues as it has been tackled here: https://github.com/MystenLabs/walrus-sites/issues/220

In short, we went with the approach of using a `ws-resources.json` file that contains the routing rules. Until now, we only use a simple wildcard suffix. 

In the near future we could use the nginx rewrite rules as @rjs-mysten pointed out; trie also.
