### ISSUE TITLE
[Bug]: Unable to fetch landing page on server portal

### ISSUE THREAD

**Issue by Tzal3x** [MystenLabs/walrus-sites#147]
### What happened?

When browsing on `http://portal.name/` the walrus sites landing page should be displayed. 

At the moment this is not possible, creating infinite loops on the server. 

### Search terms

x

### Steps to reproduce

1. Deploy the server portal: `cd portal/server && pnpm run dev`
2. Access http://localhost:3000

### Version

- [X] `walrus` and `site-builder` are up to date.

### If applicable, what browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by giac-mysten** [comment]
Closed by #148 and #153
