### ISSUE TITLE
[Refactor]: Rename the landing page indexes

### ISSUE THREAD

**Issue by Tzal3x** [MystenLabs/walrus-sites#179]
### Description

Both server portal and service-worker portal should use an `index.html` file as their main landing page. 

Currently there are `index-sw-enabled.html` and `index.html` used. 

`index.html` is only used temporarily by the service worker until it gets registered. 
`index-sw-enabled.html` is used by both portals as the main landing page.

We should rename `index-sw-enabled.html` to `index.html` and `index.html` to `index-sw-not-enabled.html`. 

### Component

portal

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by Tzal3x** [comment]
> Consider doing the following: [#174 (comment)](https://github.com/MystenLabs/walrus-sites/pull/174#discussion_r1725460897)

Explicit is better than implicit, and in this case doing a `mv temp-landing-page/index-sw-enabled.html temp-landing-page/index.html` in the publish landing page script would confuse anyone who would search for the source code of the landing page (except if they checked the publish script too).

**Comment by giac-mysten** [comment]
the alternative is to have a separate set of files called idk `published-landing`, and then have webpack do the correct moving around... but for now `mv` is fine :)
