### ISSUE TITLE
The portal not found page links to walrus.site instead of blob.store

### ISSUE THREAD

**Issue by giac-mysten** [MystenLabs/walrus-sites#190]
It should instead link to the root url of the portal.

<img width="505" alt="image" src="https://github.com/user-attachments/assets/93a7412f-5c8f-4a7f-9d47-94ad407bb9c6">

**Comment by Tzal3x** [comment]
That's happening because the service worker and the server portal both use the same html files. Need to add a mechanism that parses the URL to identify what's the current portal, and use the correct hyperlink.
