### ISSUE TITLE
Support more content encoding options

### ISSUE THREAD

**Issue by Tzal3x** [MystenLabs/walrus-sites#199]
### Description

[Currently we only support PlainText](https://github.com/MystenLabs/walrus-sites/blob/aaeab22b70b3ecb736d59d38e4dbc92bd4274042/site-builder/src/site/content.rs#L11-L15). Update the script so that we also include `gzip` and `deflate`.

⚠️ This change might break user-facing parts. Please test thoroughly❗   

### Component

site-builder

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by giac-mysten** [comment]
Closing as we decided to rely on lower-layer optimizations for compression

**Comment by giac-mysten** [comment]
this should be closed, see above
