### ISSUE TITLE
Add full-node fallback list

### ISSUE THREAD

**Issue by Tzal3x** [MystenLabs/walrus-sites#211]
We could add load balancing routing on the portal side, i.e. monitor the available full nodes from it and pick the first available one in order of preference. 

Suggestion: add the possibility for users to pick their own trusted full node. 

Recommended full nodes:

```
Triton One
DSRV (All that node)
ANKR
Bware
Blockvision
```

**Comment by mario4tier** [comment]
Sharing here that I have already develop a sui nodes proxy for network robustness (as part of a Sui foundation grant).

It is running by default for devs using Suibase. Your app just use a local daemon port and it "just work" (there is one port for testnet, another for mainnet etc...).

I understand you might prefer to have your own in-house solution, just a FYI.

What does it do?
================
- Configurable Full-nodes list (hot-reloaded without traffic disruption). 
- Periodic monitoring of configured nodes (e.g. average response time to a health check).
- Real-time "best nodes" subset for load-balancing (see "green" in picture).
- Automatic failover/retry, which is also "sui-aware" to prevent equivocation.
- Open-source (Rust, tokio optimized).

![image](https://github.com/user-attachments/assets/52a4f6da-5179-40bf-ada2-3478c8f1c771)

**Comment by Tzal3x** [comment]
Thank you @mario4tier, we will consider your suggestion! 👍
