### ISSUE TITLE
The blob is not being downloaded.

### ISSUE THREAD

**Issue by daoauth** [MystenLabs/walrus-sites#274]
### What happened?

The blob is not being downloaded. Even after updating, the same issue occurs.

https://noj7llhl2gvohwk871217cahlis85jozc59vv9bf2ntdn11x4.walrus.site/

The console shows ‘has been blocked by CORS policy,’
<img width="928" alt="Screenshot 2024-10-24 at 2 00 02 PM" src="https://github.com/user-attachments/assets/600a2d30-0031-4c22-82d5-f51a4405d5e1">

 and in the network tab, a 404 error is displayed.
<img width="927" alt="Screenshot 2024-10-24 at 2 00 18 PM" src="https://github.com/user-attachments/assets/db3c36bf-47ff-47fc-a67a-3b74173bb906">

When deploying a new site, this problem does not occur.

https://1b1ptk945jo3fd9iymuvwz29ll8r5mofysukykc65qd9oxnnwo.walrus.site/

After redeploying, the blob became readable again. Upon checking the problematic blob, I discovered that the age had been reset(?).

https://walruscan.com/testnet/blob/jaglWb0RDb8Ln9ogCzZZYHRIMDzzfwRoamuwpizNpOQ
<img width="1344" alt="Screenshot 2024-10-24 at 2 15 50 PM" src="https://github.com/user-attachments/assets/1882c4aa-91ba-478a-be97-9e5dc241262c">

I don’t have a screenshot of the previous object, but its age was 6. It seems a policy regarding the lifespan of all Blob objects used on the webpage after an update is necessary. The issue likely arises because updated objects are refreshed, but unmodified objects retain their previous lifespan.

Additionally, I checked that the blob was refreshed when the CSS was updated during the redeployment.

<img width="1332" alt="Screenshot 2024-10-24 at 2 56 52 PM" src="https://github.com/user-attachments/assets/3512f4d6-76f1-403f-8f5e-2d0423077ba9">

I’m not sure how the Blob ID is assigned, but from my observations, it seems that the ID is issued to allow sharing of the same Blob object ID within the account ([0x8d94f4d3a53fedd35abb0244640db57fd3439e06aeab728c2e8ad4c4ba62abae](https://suiscan.xyz/testnet/object/0x8d94f4d3a53fedd35abb0244640db57fd3439e06aeab728c2e8ad4c4ba62abae), [0x0447af0ff6ec05b31a32bd4e351780bdd0110463e494717a2d2594ef06c3d50e](https://suiscan.xyz/testnet/object/0x0447af0ff6ec05b31a32bd4e351780bdd0110463e494717a2d2594ef06c3d50e)). However, I’m curious whether the same Blob ID is generated when different users use the same library.

### Search terms

issues?q=blob

### Steps to reproduce

https://github.com/zktx-io/walrus-pass-monorepo/actions/runs/11475670797/job/31934009186

### Version

- [X] `walrus` and `site-builder` are up to date.

### If applicable, what browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by giac-mysten** [comment]
Hi @daoauth . When you `update` a site, any resource that has been changed needs to be uploaded to a new blob on walrus. This blob will have a different blob ID (think of the blob ID as a hash of the content, more info in the docs). 

However, the newly uplaoded blob will have the number of epochs specified by the `--epochs` flag when you run the `update` command, which was (this has been recently changed) `1` by default. 

If you realize you have made a mistake, please run `update --epochs <CORRECT> --force` to force all blobs to expire at the wanted number of epochs ahead.
