### ISSUE TITLE
Allow SuiNs subdomains to work with the service worker

### ISSUE THREAD

**Issue by giac-mysten** [MystenLabs/walrus-sites#32]
for example `nft1.myproject.walrus.site`. 
This also allows to programmatically add site names on mint.

**Comment by Tzal3x** [comment]
Currently suins names don't support dots: 
![image](https://github.com/user-attachments/assets/0be35b52-188d-43e5-9bd4-e94141297b9d)
You can test it out here: https://testnet.suins.io/account/my-names#your_name
