### ISSUE TITLE
bug: Deserialization failed by walrus

### ISSUE THREAD

**Issue by lispking** [MystenLabs/walrus-sites#322]
### What happened?

walrus info --dev
2024-12-10T01:51:24.813490Z  INFO walrus: client version: 1.5.0-8071a774cc01

Error: Parse error: Deserialization failed at line 1 column 68: Deserialization failed at line 1 column 68

### Search terms

/issues?q=state:open+type:issue+sort:created-asc+Deserialization_failed

### Steps to reproduce

Example:
1. Publish site with the following contents: [...]
2. Navigate to the site at [...]
3. Press [...]

### Version

- [X] `walrus` and `site-builder` are up to date.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by giac-mysten** [comment]
Thanks for the report @lispking ! this is not a walrus sites issue, but rather a walrus/sui issue due to some incompatibilities in the sdks after some recent upgrades.

We are already onto solving the issue!

**Comment by lispking** [comment]
> Thanks for the report @lispking ! this is not a walrus sites issue, but rather a walrus/sui issue due to some incompatibilities in the sdks after some recent upgrades.
> 
> We are already onto solving the issue!

aha, Since the walrus has not been open-sourced yet, that's all that can be mentioned here.

**Comment by sailplaneTW** [comment]
> Thanks for the report @lispking ! this is not a walrus sites issue, but rather a walrus/sui issue due to some incompatibilities in the sdks after some recent upgrades.
> 
> We are already onto solving the issue!

Hello, I have the same issue too ~
Wait for your fix ~
Thx a lot !

<img width="1082" alt="截圖 2024-12-11 晚上8 13 08" src="https://github.com/user-attachments/assets/340d4755-593f-4d0e-8bed-167d2bdd45fa">

**Comment by giac-mysten** [comment]
Hello @sailplaneTW @lispking .
if you now upgrade to the latest version of the `site-builder`, as well as the lates version of the `walrus` client, this issue should be resolved!

**Comment by lispking** [comment]
But the updated version is still `1.5.0-8071a774cc01`, so the problem has not been solved. And it is not feasible to find other test nodes either, such as `https://sui-testnet.public.blastapi.io:443`

**Comment by sailplaneTW** [comment]
@giac-mysten 

Hello, I have re-downloaded walrus and builder and all is OK !
site-builder: site-builder 1.0.1-4583aa0c096d
walruis: walrus 1.6.3-9cbc0e4e5055

Btw, I am clean all env and rebuild with my notes : [https://www.sam-huang.info/deploy-your-own-website-to-sui-walrus_en/](https://www.sam-huang.info/deploy-your-own-website-to-sui-walrus_en/)

<img width="960" alt="截圖 2024-12-12 中午12 03 30" src="https://github.com/user-attachments/assets/cd7a2ab9-52a1-4b90-ac5a-e0e21e17ded0" />

**Comment by lispking** [comment]
> hello @giac-mysten @lispking
> 
> I have re-downloaded walrus and builder and all is OK ! site-builder: site-builder 1.0.1-4583aa0c096d walruis: walrus 1.6.3-9cbc0e4e5055
> 
> Btw, I am clean all env and rebuild with my notes : https://www.sam-huang.info/deploy-your-own-website-to-sui-walrus_en/
> 
> <img alt="截圖 2024-12-12 中午12 03 30" width="960" src="https://private-user-images.githubusercontent.com/1217194/395003378-cd7a2ab9-52a1-4b90-ac5a-e0e21e17ded0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzY4OTQsIm5iZiI6MTczMzk3NjU5NCwicGF0aCI6Ii8xMjE3MTk0LzM5NTAwMzM3OC1jZDdhMmFiOS01MmExLTRiOTAtYWM1YS1lMGUyMWUxN2RlZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTJUMDQwOTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2JjNDAwNTJhODgzMWQxMjhkYjY1Y2QwYTlmYjg4ZjYyYjJlYjY0NDBhMmRiNjI4ZjJhM2JhNDBlNmNhNzM2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3wucSfCZu9P7z7a1gNMYI0wuvFN1Mrycrw-2-py1RWM">

cool, the walrus 1.6.3-9cbc0e4e5055 is ok now

**Comment by giac-mysten** [comment]
Thank you all! Glad it's working for you too. Closing the issue for now!
