### ISSUE TITLE
Check the status of the blob on Walrus before performing operations.

### ISSUE THREAD

**Issue by giac-mysten** [MystenLabs/walrus-sites#35]
The site builder currently only checks if the blob ID on chain matches the blob ID on disk.

However, if devnet was wiped, the two can be the same but the blob may be missing.

This is currently mitigated by the `--force` flag.

**Comment by Tzal3x** [comment]
> if devnet was wiped, the two can be the same but the blob may be missing.

If devnet was wiped, how would one fetch the on-chain blobid in the first place to check the disk blob ID matches it?

**Comment by giac-mysten** [comment]
If I understand your question, the point here it that "devnet" is the Walrus devnet. The "on-chain blob ID" is on Sui _testnet_. So the `Site` and relative `Resource` objects on chain may still contain a blob ID, but the storage nodes do not have it stored.

**Comment by mlegner** [comment]
So the current behavior is the following:
- Without `--force`, do not attempt to store files on Walrus if the corresponding Walrus Sites `Resource` already exists.
- With `--force`, store all files on Walrus with the `--force` option (provided to the `walrus` binary).

What we would want to support the case that Walrus is redeployed is one of the following:
- Check the Walrus blob status for all files and store those that are not certified.
- Attempt to store all files on Walrus but _without_ using the `--force` option.
