### ISSUE TITLE
Better handling of empty files (Error: the data is empty)

### ISSUE THREAD

**Issue by kkomelin** [MystenLabs/walrus-sites#88]
When I try to publish my frontend app to Walrus Sites, I receive the following error:

```
2024-06-19T07:21:52.356360Z  INFO site_builder: initializing site builder
2024-06-19T07:21:52.356711Z  INFO site_builder: configuration loaded config=Config { portal: "walrus.site", package: 0x514cf7ce2df33b9e2ca69e75bc9645ef38aca67b6f2852992a34e35e9f907f58, general: GeneralArgs { rpc_url: None, wallet: None, walrus_binary: Some("walrus"), walrus_config: None, gas_budget: Some(500000000) } }
2024-06-19T07:21:52.356759Z  INFO site_builder::util: Using wallet configuration from /home/kos/.sui/sui_config/client.yaml
Error: running the command exited with error: 2024-06-19T07:21:59.801087Z  INFO walrus: running in JSON mode
2024-06-19T07:21:59.801167Z  INFO walrus_service::cli_utils: Using Walrus configuration from /home/kos/.walrus/client_config.yaml
2024-06-19T07:21:59.801233Z  INFO walrus_service::cli_utils: Using wallet configuration from /home/kos/.sui/sui_config/client.yaml
2024-06-19T07:21:59.801637Z  INFO walrus_service::cli_utils: Using RPC URL set in wallet configuration
Error: the data is empty
```

**Comment by kkomelin** [comment]
Reproduction demo is in progress. Will publish here shortly

**Comment by mlegner** [comment]
I suspect you have an empty file somewhere. But I agree, we should improve the handling of that and/or print a more useful error.

**Comment by kkomelin** [comment]
The reproduction:

Clone the reproduction repo:
```
git clone -b walrus-deploy https://github.com/kkomelin/sui-dapp-starter
cd sui-dapp-starter
```
Install the deps and run the deploy:
```
pnpm i
pnpm --filter frontend deploy:walrus
```

**Comment by kkomelin** [comment]
If it matters, I've got `robots.txt` empty in the root.

**Comment by mlegner** [comment]
> If it matters, I've got robots.txt empty in the root. But it's intentional.

That makes total sense. Walrus currently doesn't support empty files, so we either need to add support for that or handle it on the Walrus Sites side.

Until we have that, can you just add a comment line to that file as a workaround?

**Comment by kkomelin** [comment]
Yes, good idea. Will try now

**Comment by kkomelin** [comment]
Hooray! It works! https://5q9p8r84khdpdia3dnsw0pkpk3rxa0ic2kqbdlstne8vu2t192.walrus.site/

Thank you very much for you help!

I will try to debug one more issue with configuration and report if I can reproduce.

**Comment by giac-mysten** [comment]
Thanks @kkomelin , this is a known "area of improvement" :) 

> That makes total sense. Walrus currently doesn't support empty files, so we either need to add support for that or handle it on the Walrus Sites side.

I would say for now the best fix would be to catch empty files in the `site-builder` and print a message saying which are the empty files, and either to add something to them or remove them. The same could be done for unknown extensions.

**Comment by kkomelin** [comment]
Thanks @giac-mysten,
As for empty files, I agree with your solution.
As for .webmanifest filename, it's just a JSON. Browsers just use the extension to set higher level mime type for it. So I would still insist on adding support for it if it's easy to do.

**Comment by giac-mysten** [comment]
>So I would still insist on adding support for it by default if it's easy to do.

of course! We just need to have a clear boundary of files/file types we support directly + a good fallback strategy, so that we don't end adding a new file type every day :)

But this will be surely fixed.

**Comment by kkomelin** [comment]
@giac-mysten Yeh, I understand. And it's important to collect more requests for this particular file extension from the community before implementing it.

**Comment by Tzal3x** [comment]
Hey, if nobody is working on this, can I be assigned to it?

**Comment by giac-mysten** [comment]
Yes @Tzal3x , go ahead. Thank you!
