### ISSUE TITLE
Present error message on browsers that don't support service workers (e.g., iOS in-app browser)

### ISSUE THREAD

**Issue by kkomelin** [MystenLabs/walrus-sites#91]
I tried to open two web apps, hosted on Walrus Sites, in the internal Sui Wallet browser (Apps tab) on iPhone SE 2:
1) https://suidappstarter.walrus.site/
2) https://flatland.walrus.site/

And experienced the same behavior with both apps. The app is constantly loading with a message "just a moment". See screenshot attached.

![IMG_0324](https://github.com/MystenLabs/walrus-sites/assets/755066/53837c64-4e81-4cce-b130-417033aa21f8)

Maybe it's an infinite loop or something like that.

Chrome and Safari on iPhone load the app with no issues.

---

**Since in-app browsers on iOS are [not supported](https://docs.walrus.site/walrus-sites/restrictions.html#ios-sui-mobile-wallets-do-not-work-with-walrus-sites), It would be good to display a more descriptive error message.**

**Comment by mlegner** [comment]
This is an unfortunate limitation of the in-app browser on iOS, see [here](https://docs.walrus.site/walrus-sites/restrictions.html#ios-sui-mobile-wallets-do-not-work-with-walrus-sites).

**Comment by kkomelin** [comment]
Ah, I see. Thank you @mlegner.

Can we display an error message instead of the infinite loading?

**Comment by mlegner** [comment]
> Can we display an error message instead of the infinite loading?

That's a good idea! 👍

**Comment by kkomelin** [comment]
Thank you @mlegner
