### ISSUE TITLE
Mac/Chrome: Wallet connection doesn't seem to work

### ISSUE THREAD

**Issue by kkomelin** [MystenLabs/walrus-sites#96]
I've received a message from a user today that the wallet connection for the Walrus Sites deployment of Sui dApp Starter https://suidappstarter.walrus.site/ doesn't work on their Mac/Chrome.

However, the Web2 deployment is working fine for them https://demo.sui-dapp-starter.dev/

Unfortunately, I don't have a Mac machine at hand, so I'd appreciate if you guys could test and reproduce. Thank you.

**Comment by mlegner** [comment]
I just checked and cannot reproduce this. Wallet connection with Sui Wallet works fine on my macBook with Chrome.

**Comment by mlegner** [comment]
Does the user have some further details to share (error messages from the console, etc.)?

**Comment by kkomelin** [comment]
@mlegner Thanks for testing. Will try to request some more details

**Comment by giac-mysten** [comment]
@kkomelin checked as well, works for me too on macbook.

**Comment by kkomelin** [comment]
Thank for checking @giac-mysten! I will keep you guys updated if I get any new details.

**Comment by kkomelin** [comment]
No reply from the user who reported. Let's close for now and reopen/open if anyone else reports.
